services/.gitignore, services/beeja-cloud-gateway/src/main/java/com/beeja/api/apigateway/config/security/SecurityConfig.java, services/beeja-cloud-gateway/src/main/resources/application.yaml
This PR resolves the **CORS issue** that was preventing requests from multiple hosts (e.g., localhost and domain.com). The following updates have been made:
- Configured global CORS settings in the API Gateway to allow requests from localhost.
- Enabled allowedOriginPatterns instead of allowedOrigins for more flexible domain handling.
- Allowed all standard HTTP methods (GET, POST, PUT, DELETE, OPTIONS).
This fix ensures seamless API access from multiple frontend hosts during development.
=> fix: cleared cors issue to accept request from multiple hosts

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/LoanServiceImpl.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/serviceImpl/BulkPayslipUploadTest.java
This PR introduces improvements to the bulk payslip upload functionality.
- Validated each file inside the ZIP for ( Missing file name, Unsupported file type (non-PDF), Missing or unrecognized Employee ID)
- Handled corrupted or unreadable ZIP files using proper exception handling.
- Ensured individual file failures don’t stop the overall process.
- Added clear success and failure logs for each file.
- Added JUnit test cases for the uploadBulkPaySlips method.
=> Fix issue in bulk payslip upload functionality

services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/controllers/ApplicantController.java, services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/response/ApplicantDTO.java, services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/response/PaginatedApplicantResponse.java, services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/service/ApplicantService.java, services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/serviceImpl/ApplicantServiceImpl.java, services/beeja-recruitment/src/test/java/tac/beeja/recruitmentapi/serviceImpl/ApplicantServiceImplTest.java
This PR improved the List of Applicants API by adding pagination and sorting to enhance performance and optimize data retrieval.
Changes Made:
- Added pagination support using page and limit parameters to fetch data in smaller chunks.
- Implemented sorting functionality with sortBy and sortDirection for dynamic ordering of results.
- Applied filtering criteria for applicant details such as applicantId, firstName, positionAppliedFor, status, experience, and createdDate.
- Included metadata in the response, such as totalRecords and totalPages, to assist frontend integration.
- Set a default page size (10 applicants per page) and a maximum limit to prevent excessive data retrieval.
=> Implemented Pagination Support for List of Applicants API

web/src/screens/InventoryManagement.screen.tsx
- Issue:
The availability filter in the Inventory Management screen caused a continuous loading state when toggled or reset.
- Root Cause:
The filter included a default value ("availability") in the API query, which led to incorrect filtering and prevented data fetching.
- Fix:
Added a condition to exclude the default "availability" value from the query.
=> fix:fixed Availability Filter

services/beeja-accounts/src/main/java/com/beeja/api/accounts/mongo/OrgDefaultsChecks.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrganizationServiceImpl.java
This PR addresses an issue where the organization update API was failing due to duplicate values in OrgDefaults.
To resolve this, I implemented the following:
- On application startup (@PostConstruct),all OrgDefaults records were scanned.
- Duplicate OrgValues (case-insensitive) were removed.
- Only unique values were retained and saved back to the database.
- The logic was implemented asynchronously (@Async) to avoid blocking the startup process.
=> fix : Organization Defaults Update API Failure

web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx
This PR Introduced:
-  This enhancement addresses a UX issue where the Employee ID field in the "Job" section appeared editable, causing confusion among users.
- Although the field was not meant to be modified, its editable appearance implied otherwise.
=> fix:Remove Editable Appearance

web/src/screens/InventoryList.screen.tsx, web/src/screens/InventoryManagement.screen.tsx
**This PR introduced:**
- Resolved an issue where non-device filters (e.g., “Available” or “Provider”)
- were not shown under the “Applied Filters” section unless a device filter was also selected.
- Also fixed the UI not updating to show “No filters applied” after clearing all filters.
=> fix : Fixed UI Issue in Filter Section

web/src/components/reusableComponents/MyProfileKYCTabContent.component.tsx, web/src/components/reusableComponents/MyProfileTabsContainer.component.tsx
This PR includes :
When an employee or privileged user selects the KYC tab, the page heading is displaying correctly.
After saving a bank account number, re-entering Edit mode it was showing the correct saved value, not "0" or any placeholder.
=> Fixed UI issues in KYC tab navigation and in Bank Account number

services/beeja-expense/src/main/java/com/beeja/api/expense/ExpenseManagementApplication.java
This PR Introduces :
- While creating a new expense, the createdAt field was not being assigned manually in the createExpense method.
- Because of this, sorting by createdAt was not working properly when fetching expenses.
- I implemented @EnableMongoAuditing to automatically populate the createdAt field at the time of expense creation.
- After this change, the createdAt field was correctly populated, and sorting by creation date started working as expected.
=> fix : sort by createDate in expense service

services/beeja-recruitment/src/main/resources/static/openApi.yaml
- Integrated Springdoc OpenAPI 3.0.1 for API documentation.
- Created detailed openApi.yaml covering all applicant and referral endpoints.
- Added summaries, request/response schemas, and status codes for all APIs.
- Grouped endpoints using tags like Applicants and Referrals.
- Configured Swagger UI at :- http://localhost:8000/recruitments/swagger-ui/index.html
- Defined all necessary models under components/schemas.
=> feat:Configured Swagger API for Recruitment Service

web/src/components/directComponents/LoanPreview.component.tsx, web/src/utils/dateFormatter.ts
This PR introduces 
Fixed the display issue of a loan preview when the loan list have 'created at' value is null .
=> fix: fixed the handle null createdAt in loan preview

web/src/components/reusableComponents/MyProfileTabsContainer.component.tsx
User can stay in the same screen after updating the job details. it will not redirect to general Tab.
=> Bugfix: fixed auto redirect to general tab when updating job fields

web/src/components/reusableComponents/DocumentAction.tsx, web/src/components/reusableComponents/ExpenseListAction.tsx, web/src/components/reusableComponents/ExpenseTyeAction.tsx, web/src/components/reusableComponents/InventoryListAction.component.tsx
- Fixed false active state for action buttons – ensured only the currently active action button is highlighted (greyed out), and others are reset.
- Improved UI feedback consistency – updated button states to reflect the latest user action, preventing misleading visual states.
=> fix:fixed action button highlight state across all modules

web/src/screens/LoanManagementScreen.screen.tsx, web/src/screens/RecruitmentManagementScreen.screen.tsx
fixed: when the referral data list is empty pagination controls are not displayed.
=> fix:Hide Pagination Controls When Referral List is Empty

web/src/screens/LoanManagementScreen.screen.tsx, web/src/screens/OrganizationSettings.screen.tsx
This PR introduces: 
1. Fixes the issue where newly added modes of payment under Settings > Expense > Mode of Payments were not reflected in the Expense module. 
2. The update ensures that these entries now appear in both the filter dropdown and the Add Expense form, maintaining consistency and allowing users to select the newly created modes.
=> Fix Newly added mode of payment with Expense module filters and forms

web/src/components/directComponents/AddInventoryForm.component.tsx, web/src/styles/ExpenseManagementStyles.style.tsx
This PR Introduced:-
1. Implemented conditional logic to enable and validate OS and RAM fields only for devices that support them (e.g.,  Laptop, Desktop, Mobile, Tablet,).
2. Disabled fields now display in light grey to indicate non-applicability, improving user experience and form accuracy.
=> Fix: Conditionally enable OS and RAM fields based on selected device type

services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/EmployeeServiceImpl.java, services/beeja-employee-management/src/main/java/com/beeja/api/employeemanagement/serviceImpl/EmployeeServiceImpl.java
- Fixed the issue where the employmentType field was not being saved or returned properly in employee records after creation.
- Updated the relevant service methods to ensure employmentType is correctly handled during employee creation and retrieval.
=>  Fix: Employment type not shown in employee records post creation

services/beeja-recruitment/src/main/java/tac/beeja/recruitmentapi/response/ApplicantDTO.java
This PR updates the Applicant DTO by renaming a field to referredByEmployeeName to display the referral employee's name in the 'List of Hiring' section
=> Fixed displaying the Referral Employee name in recruitment List

web/src/components/reusableComponents/MyProfileTabsContainer.component.tsx
- Removed localStorage/sessionStorage logic used for persisting the selected tab in the profile component.
- Ensured the tab resets to "general" when switching between employee profiles by relying on default component state.
=> fix:Reset profile tab to 'general' on employee change

web/src/components/reusableComponents/TopNavBar.component.tsx
Fix: Removed Navigation Links (documents and payslip) from top-NavBar
Structural Integrity is maintained for the remaining top-NavBar.
Comments have also been added in the files for easier fixing later.
=> Fix/Remove-Nav-Links for (documents and payslip) 

services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrgDefaultsGenerationImpl.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrganizationServiceImpl.java
This PR Introduced:
- Implemented logic to auto-generate default document types (Identity, PaySlip, NDA, Appraisal Letter, Equipment Policy, Address Proof, Tax Exit Doc.
=> Generated the Default Document types

web/src/components/directComponents/EditInventory.component.tsx
Fix: Device-Type is displayed when the edit form is opened in Inventory.
=> Fix: Device Type Display while editing form in Inventory

web/src/styles/EmployeeListStyles.style.tsx
The Employee List page title is now in the standard font size which is applied to all other module headers.
=> bugfix: fixed Font Size for Employee List Page Title

web/src/components/reusableComponents/DropDownMenu.component.tsx, web/src/styles/MyProfile.style.tsx
- Fixed an issue where the dropdown did not display the previously selected value in edit mode.
- Adjusted the alignment of the calendar icon in the Joining Date field of the job section to ensure proper spacing and consistent layout with the input field.
=> fix: preserve selected value in dropdown during edit mode
