beeja-io/beeja

.gitignore, web/src/components/reusableComponents/CenterModal.component.tsx
Original PR of https://github.com/beeja-io/beeja/pull/86
=> fix: fixed model button functionality

services/beeja-accounts/src/main/java/com/beeja/api/accounts/controllers/OrganizationController.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/repository/OrgDefaultsRepository.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/service/OrganizationService.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrganizationServiceImpl.java
Added API to get required organization values based on keys
=> feat: added API to get all values based on given list of IDs

web/src/constants/RoleData.ts
Extended permission list in add and update role screens
=> enhancement: Added Permissions of Recruitment Management in Add/Edit Role Screens

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/client/FileClient.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/controllers/ClientController.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/Client.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/dto/File.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/ClientRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/FileUploadRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/responses/FileResponse.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ClientServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java, services/beeja-projects/src/main/resources/application.yaml
Updated add client API request body to accept proper MultipartFile (logo)
=> enhance: updated client id business logic in add client API

services/beeja-accounts/src/main/java/com/beeja/api/accounts/controllers/EmployeeController.java, web/src/components/reusableComponents/MyProfileQuickDetails.component.tsx, web/src/service/axiosInstance.tsx
Ensured that the roles state in `MyProfileQuickDetails.component.tsx` is initialized correctly and retains previous roles when updating.
=> fix: add role issue fixed

web/src/screens/EmployeeList.screen.tsx
removed status filter for employees now, it will visible for super admin, HR, beeja admin not visible for employee
=> reomved status filter for employess

web/index.css, web/src/components/reusableComponents/LoanListView.compoment.tsx, web/src/locales/en/translation.json, web/src/screens/EmployeeList.screen.tsx, web/src/screens/InventoryManagement.screen.tsx, web/src/screens/Theme&Typography.screen.tsx, web/src/styles/ExpenseListStyles.style.tsx, web/src/styles/MyProfile.style.tsx, web/src/styles/ThemeTypography.style.tsx
This Pr introduce......
1. Resolved the displaying the validation message in editing the profile.
2. Email Display & Alignment in Profile: Fixed the visibility and alignment of the email field under the Profile section to display properly.
3. fixed the DOB field, where it show the previous value while editing.
4. fixed typography in organization settings
5. Made the Lon list to render in the sorted manner by its date of creation.
6. fixed the action menu with options edit and delete in different sections of organization settings.
7. In inventary Management, fixed the adding of latest inventary on the top of the list.
8. Fixed the translations in the employeelist.
=> Resolve all the bugs listed in the latest bug report

services/beeja-expense/src/main/java/com/beeja/api/expense/controllers/ExpenseController.java, services/beeja-expense/src/main/java/com/beeja/api/expense/service/ExpenseService.java, services/beeja-expense/src/main/java/com/beeja/api/expense/serviceImpl/ExpenseServiceImpl.java, web/src/components/directComponents/AddExpenseForm.component.tsx, web/src/entities/ExpenseEntity.tsx, web/src/locales/en/translation.json, web/src/screens/ExpenseList.screen.tsx
Added new filter in Expense Management. It is used to fetch records based on Payment Settled Date
=> enhance: expense filters - added settled status filter

services/beeja-accounts/src/main/java/com/beeja/api/accounts/controllers/OrganizationPatternController.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/service/OrganizationPatternService.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrganizationPatternServiceImpl.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/client/AccountClient.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/modals/Loan.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/modals/clients/finance/OrganizationPattern.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/repository/LoanRepository.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/LoanServiceImpl.java, web/src/components/reusableComponents/LoanListView.compoment.tsx
Enhanced Loan Id Generation Logic in finance service
- Now loan id is generated based on org. default values
=> enhance: enhanced load ID generation

web/src/components/directComponents/SettingsTypes.component.tsx, web/src/screens/OrganizationSettings.screen.tsx
Bug fixed at Organization Settings.
- Changed Endpoint from jobTypes to jobTitles.
- Added filter method so that we will not receive any empty jobTitles in UI.
=> fixed-bug-at-jobTitles

web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx
Fixed date value issue occurred while editing employee's DOB
=> fix: fixed date value issue in employee profile edit screen

web/src/components/directComponents/ApplicantsList.component.tsx, web/src/components/reusableComponents/CompleteNavBar.component.tsx, web/src/locales/en/translation.json, web/src/screens/RecruitmentManagementScreen.screen.tsx
- Renemaed Module Name is side nav bar and Hiring Screen
- Updated list headers in referral screen
- Update button name [ Add Applicant]
=> fix: cleared ui issues in hiring management

web/src/components/reusableComponents/CompleteNavBar.component.tsx
- updated holiday list url in side nav bar
=> fix: holiday list url in side nav bar

web/src/service/axiosInstance.tsx
Made changes at API End Points. Now the user can GET, POST and PUT the Data.
=> Fixed_HealthInsurance_Deduction

services/beeja-accounts/src/main/java/com/beeja/api/accounts/enums/SubscriptionName.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/repository/RolesRepository.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/SuperAdminPermissionUpdater.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/utils/Constants.java, services/beeja-accounts/src/main/resources/permissions/AllPermissions.json, services/beeja-accounts/src/test/java/com/beeja/api/accounts/serviceImpl/SuperAdminPermissionUpdaterTest.java
This PR introduce :
- Implemented a validation mechanism to ensure the Super Admin has all permissions.  
- Retrieved the complete set of permissions from the JSON file and compared them with the database.  
- Automatically updated the database with any missing permissions.  
- Assigned missing permissions to the Super Admin role to maintain full access.  
- Integrated the update process to run asynchronously during application startup.
=> Validate and grant missing permissions to Super Admin for full access

services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/SuperAdminPermissionUpdater.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/utils/Constants.java, services/beeja-accounts/src/main/resources/permissions/AllPermissions.json
- This PR Introduces :
- Checked if ALL_PERMISSIONS entry was missing in the database.
- If it was missing, created a new Permissions object with an empty set.
- Saved the new entry to the database to avoid NullPointerException.
- Added logs to track when the new permissions entry is created and saved.
=> bug-fixing-of-feature-157

web/src/screens/EmployeeList.screen.tsx, web/src/styles/InputStyles.style.tsx
Scrolling was restricted to the Add New Profile side form.
=> Fixed scrolling issue in Add new Profile Sideform

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/controllers/InventoryController.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/service/InventoryService.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/InventoryServiceImpl.java, services/beeja-finance/src/main/resources/static/openApi.yaml, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/controllers/InventoryControllerTest.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/serviceImpl/InventoryServiceImplTest.java
This PR introduce : 
- Added RAM filter functionality to the Inventory Management module, enabling filtering based on RAM specifications.
- Implemented corresponding JUnit test cases to ensure proper functionality and reliability of the RAM filter feature.
- Updated the OpenAPI documentation to reflect the new filter parameter and maintain API consistency.
=> Included RAM Filter in Inventory Management

services/beeja-expense/src/test/java/com/beeja/api/expense/service/ExpenseServiceImplTest.java, services/beeja-file-management/src/test/java/com/beeja/api/filemanagement/controller/FileControllerTest.java, services/beeja-file-management/src/test/java/com/beeja/api/filemanagement/service/FileServiceTest.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/exceptions/HealthInsuranceCreationException.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/exceptions/HealthInsuranceNotFoundException.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/controllers/HealthInsuranceControllerTest.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/serviceImpl/HealthInsuranceServiceImplTest.java, services/build.gradle, services/gradlew, services/gradlew.bat, services/sonar.properties
This PR Introduces :
- Set up SonarQube for all backend services to check code quality and security.
- Installed SonarQube locally and created a project with a token.
- Added the SonarQube plugin in build.gradle and configured the required properties.
- Ran ./gradlew sonarqube to perform code analysis.
- Ensured the analysis included bugs, code smells, vulnerabilities, and code coverage.
- Fixed existing test case errors to make the build successful.
=> Added SonarQube Setup for Backend

web/src/components/directComponents/SettingsTypes.component.tsx, web/src/components/reusableComponents/CenterModal.component.tsx, web/src/components/reusableComponents/MyProfileQuickDetails.component.tsx, web/src/components/reusableComponents/TopNavBar.component.tsx, web/src/screens/iDPatternCreate.screen.tsx, web/src/styles/CenterModalStyles.style.tsx
Fixed-UI-Modifications-in-Employee-Management
=> Fixed-UI-Modifications-in-Employee-Management

web/src/components/reusableComponents/MyProfileDocumentTabContent.component.tsx, web/src/styles/DocumentTabStyles.style.tsx
Scrolling is now  restricted to the Upload Document side form. The list of documents are remained static while interacting with the form.
=> Fixed scrolling issue in upload document

web/src/screens/ExpenseManagement.screen.tsx
This PR includes after submitting the expense form spinner stops
=>  Fix Expense form submission: modal not closing and spinner not stopping

services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/EmployeeServiceImpl.java
- A small fix during new employee creation — added a null check before applying equalsIgnoreCase on organization defaults.
=> fixed_issue_of_creation_new_employee

web/src/components/directComponents/AddExpenseForm.component.tsx
Now user can check Payment settled date after creating new expense and also edit it.
=> Fixed_Payment_Settled_Date

services/beeja-cloud-gateway/src/main/resources/application.yaml, services/beeja-recruitment/src/main/resources/application.yaml
This PR Introduces :
1. **Fixed API Gateway Build Failure:**
- Modified the YAML file for the API Gateway to resolve build issues, ensuring it ran successfully.
2. **Corrected Recruitment File Size Declaration:**
- Fixed the incorrect placement of the size declaration in the recruitment YAML file to ensure proper configuration.
=> fix : modified application.ymls in apigateway and recruitment services

web/src/components/directComponents/SettingsTypes.component.tsx, web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx, web/src/screens/InventoryManagement.screen.tsx, web/src/screens/iDPatternCreate.screen.tsx
User can now move to Previous ID pattern List Screen from Create ID Pattern Screen when clicked on Cancel Button.
=> Cancel_functionality_for_ID_Pattern

web/src/screens/ExpenseList.screen.tsx, web/src/styles/ExpenseListStyles.style.tsx
This PR Introduces: - 
-  A dynamic filter panel enabling privileged users to multi-select Departments, Categories, Expense Types, and Payment Modes to refine the expense list. 
- It integrates with the backend API to fetch and display filtered expenses and their total, which is shown prominently in the top-right corner.
=> enhance: added checkboxes in expance filters

web/src/components/reusableComponents/DocumentAction.tsx, web/src/components/reusableComponents/ExpenseListAction.tsx, web/src/components/reusableComponents/InventoryListAction.component.tsx, web/src/components/reusableComponents/MyProfileQuickDetails.component.tsx, web/src/components/reusableComponents/TopNavBar.component.tsx, web/src/components/reusableComponents/UserRolesListAction.tsx
- Fixed "No" functionality for pop-ups throughout the application.
- Ensured consistent user experience and prevented unintended actions.
=> fixed no button functionality

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/exceptions/GlobalControllerAdvice.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/FileUploadRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ClientServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ProjectServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java
This PR introduces :
- I removed hardcoded strings in the beeja-projects service and replaced them with constants. 
- I also organized the constants file by grouping related constants in a proper order for better readability and maintainability.
=> refactor : replace hardcoded strings with constants

services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/controllers/ClientControllerTest.java, services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/controllers/ContractsControllerTest.java, services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/controllers/ProjectsControllerTest.java, services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/serviceImpl/ClientServiceImplTest.java, services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImplTest.java, services/beeja-projects/src/test/java/com/beeja/api/projectmanagement/serviceImpl/ProjectServiceImplTest.java
- Implemented JUnit test cases for controllers and services in the beeja-project service
- Achieved unit test coverage of 80% 
- Used JUnit for all test implementations
- Covered edge cases and error scenarios adequately
- Verified code coverage using the "Line" column in the coverage report
=> enhance : Implemented Junit test cases for beeja-project service

web/src/screens/ExpenseList.screen.tsx, web/src/styles/ExpenseListStyles.style.tsx
This PR introduces :- 
- When we click on the outside of the dropdown filter, the dropdown will close automatically , even you click on other dropdown also. 
- Also made changes to the filter Calendar .
=> enhance: dropdown_filter_close_effect in expense

services/beeja-projects/build.gradle, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/controllers/InvoiceController.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/enums/InvoiceStatus.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/Invoice.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/repository/InvoiceRepository.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/FileUploadRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/InvoiceRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/service/InvoiceService.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/InvoiceServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/InMemoryMultipartFile.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/PdfGenerationUtil.java
Added APIs for invoice generation
=> apis: invoice generation apis

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/CustomErrorDecoder.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/FeignClientInterceptor.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/PermissionAspect.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/filters/AuthorizationFilter.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/filters/JwtProperties.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/controllers/ContractsController.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/controllers/ProjectsController.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/repository/ClientRepository.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/repository/ContractRepository.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/repository/ProjectRepository.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/service/ClientService.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/service/ContractService.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/service/ProjectService.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ClientServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ProjectServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/BuildErrorMessage.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/JwtUtils.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/UserContext.java
This PR introduces :
1. Added JavaDoc comments to all public classes, methods, and interfaces within the beeja-projects service.
2. Detailed JavaDocs cover:
- Purpose and functionality of methods and classes.
- Parameters, return values, and exceptions thrown.
- Important implementation notes, where applicable.
3. Followed standard JavaDoc formatting and tag usage (@param, @return, @throws, etc.).
4. Ensured consistency in tone, grammar, and structure across the documentation.
=> enhance : Created JavaDocs for beeja-projects Service

services/beeja-projects/src/main/resources/static/openApi.yaml
This PR Introduces : 
- Swagger/OpenAPI documentation for the beeja-projects backend service, providing comprehensive API documentation and an interactive interface for developers.
=> enhance:Swagger/OpenAPI is configured for the beeja-projects service

services/beeja-projects/src/main/resources/static/openApi.yaml
This PR Introduces: 
Added Required Fields in the Client Request in OpenApi documentation of adding client.
=> bugfix: Required Fields missing in ClientReqest

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/response/LoanDTO.java
This PR Introduces 
Fixed the issue of "Displaying Loan Detailed View" and also "Requested date" display in Loans Section (Payroll).
=> fix: Loan Detailed View Display

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/LoanServiceImpl.java
Renamed 'Employee Id' to 'Employee Code' in the backend logic for Bulk Pay Slips module
=> Rename Employee Id with Employee Code in Bulk Pay slip

web/src/styles/ExpenseListStyles.style.tsx
- Fixed Edit button appearance in expense settings actions.
- Now user can easily perform edit action without any issue.
=> fix:fixed edit button appearence in expence settings

services/beeja-accounts/src/main/java/com/beeja/api/accounts/model/Organization/Accounts.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/model/Organization/BankDetails.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/model/Organization/Organization.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/requests/OrganizationProfileUpdate.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/response/OrganizationResponse.java, services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/OrganizationServiceImpl.java, services/beeja-employee-management/src/main/java/com/beeja/api/employeemanagement/model/clients/accounts/OrganizationDTO.java, services/beeja-projects/build.gradle, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/client/AccountClient.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/config/filters/AuthorizationFilter.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/Invoice.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/InvoicePeriod.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/PaymentDetails.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/Task.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/InvoiceRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/InvoiceServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/AmountToWordsUtil.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/InvoicePDFGen.java
This PR Introduces :
- Implemented the new invoice PDF generation logic based on the updated template provided by the UI/UX team.
- Updated the Invoice model/entity to include all necessary fields such as client Id, project Id, payment details, due date, tax, 
and total in words etc.
- Created new models (BankDetails, InvoicePeriod, and Task etc.) to support bank info, Invoice period, and itemized task 
breakdowns in the invoice.
- Added missing organization PaymentDetails which were required in the new invoice format.
- Ensured the generated PDF includes all required data and follows the basic structure of the UI template.
- Integrated PDF generation into the existing upload flow (local storage).
=> enhance: Invoice PDF Generation Logic to Match UI-Provided Template [BE]

web/src/components/reusableComponents/MyProfileQuickDetails.component.tsx
This PR introduces 
The drag-and-drop area correctly detects and processes image files dropped onto it.
=> bugfix: enable drag-and-drop functionality for profile picture upload

web/src/components/directComponents/EditApplicant.component.tsx, web/src/components/reusableComponents/CommentsSection.component.tsx, web/src/styles/CommentsStyles.style.tsx
Applied Dark Theme Styling to Comment Section on Edit function in Recruitment Hiring Module.
=> fixed dark theme on comment section hiring

web/src/components/directComponents/AddNewApplicant.component.tsx
Fixed Input Text Visibility in Dark Mode – Candidate Details Fields
=> fixed input text visibility in dark mode

web/src/components/directComponents/EditApplicant.component.tsx
- Fixed issue where the page remained in a loading state after clicking "Comment" post-edit in the Hiring section.
- Ensured proper API response handling and loading state reset to improve user experience.
=> fix:fixed loader issue while clicking on comment button

web/src/components/reusableComponents/DocumentAction.tsx
This PR Introduce: 
1. This PR addresses the alignment issue of the Download icon within the document preview frame. 
2. The icon is now properly positioned with consistent spacing across screen resolutions and devices, ensuring a clean, uncluttered UI.
3.  This fix enhances usability by preventing overlap with the preview frame edge and maintaining visual consistency.
=> Fix download button icon alignment in document preview

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/controllers/InventoryController.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/service/InventoryService.java, services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/InventoryServiceImpl.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/controllers/InventoryControllerTest.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/serviceImpl/GetLoansWithCountMethodTest.java, services/beeja-finance/src/test/java/com/beeja/api/financemanagementservice/serviceImpl/InventoryServiceImplTest.java
This PR fixes the filtering issue for newly created devices in the Inventory Management module. The root cause was related to enum serialization, which led to inconsistencies when filtering newly added device types. To resolve this, the Device enum was refactored to a String across all relevant inventory-related classes, ensuring smooth persistence and filtering functionality. Additionally, the corresponding test classes were updated to align with these changes and to validate the filtering logic. These modifications ensure consistent behavior and improve the reliability of device filtering in the inventory system.
=> Fix filtering issue for newly created Device

web/src/components/directComponents/AddNewApplicant.component.tsx, web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx, web/src/screens/EmployeeList.screen.tsx, web/src/styles/DocumentTabStyles.style.tsx
Applied null checkers for Employye type and Job title. Changed end point at MyProfile job section as we are not receiving employee Types from that API.
=> fix:applied nullcheckers and changed job section end point

web/src/components/reusableComponents/DocumentAction.tsx
User can be now prevented from background scrolling when document preview is open
=> bugfix: fixed scrolling issue in document preview

web/src/screens/EmployeeList.screen.tsx
Fixed Employment Type Filter. Changed the end point to employeeTypes and the issue resolved.
=> fix employement type

web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx, web/src/screens/EmployeeList.screen.tsx
Applied null checkers for job title and department list so that we will not get any plain display when edit is click in job section.
=> fix:Applied null checkers for job title and department list

services/beeja-finance/src/main/java/com/beeja/api/financemanagementservice/serviceImpl/InventoryServiceImpl.java
- Fixed a bug in the Inventory module where incorrect metadata handling was affecting pagination results.
- Ensured pagination now works correctly by applying proper filters and criteria in the metadata logic.
=> fix:Fixed issue in Inventory metadata affecting pagination results

web/src/components/reusableComponents/DocumentAction.tsx, web/src/components/reusableComponents/LoanListView.compoment.tsx, web/src/components/reusableComponents/MyProfileDocumentTabContent.component.tsx, web/src/constants/Utility.ts, web/src/screens/EmployeeList.screen.tsx, web/src/screens/ExpenseManagement.screen.tsx, web/src/screens/InventoryManagement.screen.tsx
The Loan view pop-up was letting the background scroll in Edge.
=> Fix : Loans view Pop-up alignment in edge

services/beeja-accounts/src/main/java/com/beeja/api/accounts/serviceImpl/EmployeeServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/repository/ProjectRepository.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/ContractRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ProjectServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java
- Back End Implementation of Contract screen with functionalities
=> BE contract  Added

services/beeja-employee-management/src/main/java/com/beeja/api/employeemanagement/serviceImpl/EmployeeServiceImpl.java
This PR introduced:
Added support for setting the employee’s phone number during organization creation.
**Changes**
- Extracts mobileNumber from the incoming employee payload.
- 
- Validates that the number is not null or empty.
- 
- Creates a new Contact object and assigns the trimmed phone number.
- 
- Sets the Contact object on the Employee entity.
=> Added mobile number logic while creating new organization of first user

web/src/components/directComponents/DeductionsTab.component.tsx, web/src/components/reusableComponents/DropDownMenu.component.tsx, web/src/styles/DropDownMenu.style.tsx, web/src/styles/MyProfile.style.tsx
In Deduction tab, under Employee Profile.
The instalment type field dropdown was not using the dropdown component.
Fixed that dropdown.
=> Dropdown Issue about Deductions tab

web/src/components/reusableComponents/CompanyProfile.component.tsx, web/src/components/reusableComponents/MyProfileGeneralTabContent.component.tsx, web/src/entities/OrganizationEntity.tsx, web/src/locales/de/translation.json, web/src/locales/en/translation.json, web/src/screens/EmployeeList.screen.tsx, web/src/utils/formInputValidators.ts
Fix for double error message being shown in Add Employee.
Also adds the error message for department type
=> Fix: Error message in Add Employeee

web/src/components/reusableComponents/LoanListView.compoment.tsx, web/src/screens/LoanManagementScreen.screen.tsx, web/src/service/axiosInstance.tsx
Update separate endpoints for employee loans
=> bugfix:fixed Loan list view for employee

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/ClientRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ClientServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java, web/src/components/directComponents/AddClientForm.component.tsx
- Added the logic in the BE to remove the logo for a client while updating the client.
- Frontend sent the remove Logo field is true when remove logo in the UI.
=> Added the logic to remove the logo for a client

web/src/components/directComponents/AddClientForm.component.tsx, web/src/components/directComponents/AddContractForm.component.tsx, web/src/components/directComponents/AddProjectForm.component.tsx, web/src/components/reusableComponents/DropDownMenu.component.tsx, web/src/locales/de/translation.json, web/src/locales/en/translation.json, web/src/screens/ClientDetailsScreen.screen.tsx, web/src/screens/ClientManagement.screen.tsx, web/src/screens/ClientTabSection.screen.tsx, web/src/screens/ContractDetailedScreen.tsx, web/src/screens/ContractManagement.screen.tsx, web/src/screens/ProjectDetailsScreen.screen.tsx, web/src/screens/ProjectManagement.screen.tsx, web/src/styles/AddContractFormStyles.style.tsx, web/src/styles/ClientStyles.style.tsx, web/src/styles/ContractStyle.style.tsx, web/src/styles/DropDownMenu.style.tsx, web/src/styles/ProjectStyles.style.tsx
fixed few translate and fields alignment in add forms when edit is clicked.
=> bugfix:client and management

services/beeja-employee-management/src/main/java/com/beeja/api/employeemanagement/serviceImpl/EmployeeServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/service/ContractService.java, web/src/components/directComponents/EditInventory.component.tsx, web/src/components/directComponents/Pagination.component.tsx, web/src/screens/EmployeeList.screen.tsx, web/src/screens/MyProfileScreen.screen.tsx
**This PR includes the following fixes and improvements: **
- Fixed the issue with sorting by employee ID after updating an employee record.
- Resolved the navigation issue in the employee list when using page numbers.
- Corrected pagination number display and functionality.
- Fixed a bug in the Inventory Edit feature that occurred during updates.
=> Fix sorting issues like sorting, navigation, and pagination in employee List

web/src/components/directComponents/DeductionsTab.component.tsx, web/src/styles/MyProfile.style.tsx
fixed alignment issue in My Profile job section
=> bugfix:fixed job section joining date alignment

web/src/components/reusableComponents/CompanyProfile.component.tsx, web/src/utils/formInputValidators.ts
Added Validations for the fields in profile and bank info
=> bugfix: added validations for profile and bank info fields

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImpl.java, web/src/screens/InventoryList.screen.tsx
This PR introduces the following fixes:
> **Contract Module**: Resolved an issue where resource data was not handled correctly during contract editing.
> **Inventory Module:** Updated the toast message displayed when editing inventory items for improved clarity.
=> Fixed the Issue of Contract Resources and inventory toast for updation

services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/controllers/ContractsController.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/model/Contract.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/request/ContractRequest.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/serviceImpl/ContractServiceImpl.java, services/beeja-projects/src/main/java/com/beeja/api/projectmanagement/utils/Constants.java
> Implemented backend logic to handle attachments while creating and updating contracts.
> Updated controllers to accept multipart file uploads for both creation and update operations.
> Added support for removing attachments when requested
=> [BE]Added the attachment logic while adding and updating contract
